---
driver:
  name: ec2
  require_chef_omnibus: 12.10.24
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  driver:
    tags:
      Name: et-fog-default-ubuntu-1404
- name: centos-7.1
  driver:
    tags:
      Name: et-fog-default-centos-7
  transport:
    username: centos

suites:
  - name: default
    run_list: recipe[et_fog]
