Documentation:
  Enabled: false

# Disable encoding requirement
Encoding:
  Enabled: false

# The default 79 character limit is sometimes unproductive.
LineLength:
  Max: 100

SpaceBeforeFirstArg:
  Enabled: false
