---
driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: centos-6.8

suites:
  - name: default
    run_list:
      - recipe[bamboo]
    attributes:
      bamboo:
        jvm:
          minimum_memory: '64m'
        name: bamboo-dev
        backup:
          enabled: false
          ceph: false
        agent:
          data_dir: /var/bamboo-agent
          home_dir: /opt/bamboo-agent
  - name: mysql-56
    run_list:
      - recipe[bamboo]
    attributes:
      bamboo:
        jvm:
          minimum_memory: '64m'
        database:
          type: 'mysql'
          version: '5.6'
