---
driver:
  name: ec2
  require_chef_omnibus: true
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.2xlarge
  interface: public
  tags:
    Name: et_elk-ubuntu-1404
    Type: test

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environments: dev

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-92f569fa
      tags:
        Env: public

suites:
  - name: server
    run_list:
      - recipe[et_elk::server]
      - role[es_master]
      - recipe[et_elk_postop]
