---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-6.0.10
  - name: debian-7.9
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[ca-certificates::default]
    attributes:
